# This workflow will build and test a Java 8 project with Maven
# Will also test on Java 9, 11 and 13 after a PR merge
# Source: https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build on CI with Maven
on: [push]

jobs:

  # First job: build and test on Java 8
  build:
    # Skip build if commit message contains '[ci skip]' or if it's a tag push
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !startsWith(github.ref, 'refs/tags/v')"

    runs-on: ubuntu-18.04
    name: Build and test on Java 8

    steps:
      - name: Check out latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # The cache key will be the hashed contents of pom.xml, 
          # so changes to pom.xml will invalidate the cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run mvn clean verify (with jacoco, mutation testing, coveralls and sonar)
        run: |
          mvn -B -f pom.xml clean verify \
          $ENABLED_PROFILES $ADDITIONAL_GOALS \
          -D repoToken=$COVERALLS_TOKEN \
          -D sonar.host.url=$SONAR_URL \
          -D sonar.organization=$SONAR_ORGANIZATION \
          -D sonar.projectKey=$SONAR_PROJECT
        env:
          ENABLED_PROFILES: -P jacoco-report,mutation-testing
          ADDITIONAL_GOALS: coveralls:report sonar:sonar
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          SONAR_URL: https://sonarcloud.io
          SONAR_ORGANIZATION: n3d1117-github
          SONAR_PROJECT: n3d1117_book-manager
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Second job: also build on Java 9, 11 and 13, but only after merging a PR
  build-on-pr-merge:
    if: startsWith(github.event.head_commit.message, 'Merge pull request')

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [9, 11, 13]
    name: Test on other Java versions

    # Almost the same steps as first job (sadly, you can't yet reuse steps
    # with Github Actions, so duplication is inevitable here)
    steps:
      - name: Check out latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Avoid duplicated reports to sonar and coveralls
      - name: Run mvn clean verify (with jacoco and mutation testing)
        run: mvn -f pom.xml clean verify $ENABLED_PROFILES
        env:
          ENABLED_PROFILES: -P jacoco-check,mutation-testing
