# This workflow will build and test a Java 11 project with Maven
# Source: https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build on CI with Maven
on: [push]

jobs:
  
  # Second job: also build on Java 8 and 13, but only after merging a PR
  build-on-pr-merge:
    if: startsWith(github.event.head_commit.message , 'Merge pull request')
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [8, 11, 13]
    name: Build and test on Java ${{ matrix.java }}
    # Same steps as first job (sadly, you can't yet reuse steps with Github Actions, so duplication is inevitable here)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run mvn clean verify (with jacoco and mutation testing)
        run: mvn -f pom.xml clean verify $ACTIVE_PROFILES
        env:
          # Avoid reporting to sonar and coveralls
          ACTIVE_PROFILES: -Pjacoco,mutation-testing
    
    
    
