# This workflow will build and test a Java 11 project with Maven
# Source: https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          # The cache key will be the hashed contents of pom.xml, so changes to pom.xml will invalidate the cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Test project (mvn clean verify)
        run: mvn -f pom.xml clean verify
