# This workflow will build and test a Java 11 project with Maven
# Source: https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          # The cache key will be the hashed contents of pom.xml, so changes to pom.xml will invalidate the cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Run Maven clean verify
        run: mvn -f pom.xml clean verify $ACTIVE_PROFILES $ADDITIONAL_MAVEN_ARGS $COVERALLS_TOKEN
        env:
          ACTIVE_PROFILES: -Pjacoco
          ADDITIONAL_MAVEN_ARGS: coveralls:report sonar:sonar
          COVERALLS_TOKEN: -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
