# This workflow will build and test a Java 8 project with Maven
# Will also test on Java 9 and 11 after a PR merge
# Source: https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build on CI with Maven
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build and test on Java 8
    steps:
      - name: Check out latest code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java_version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          # The cache key will be the hashed contents of pom.xml, 
          # so changes to pom.xml will invalidate the cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Run mvn clean verify (with jacoco, mutation testing, coveralls and sonar)
        run: mvn -f pom.xml clean verify $ACTIVE_PROFILES $ADDITIONAL_MAVEN_ARGS $COVERALLS_TOKEN
        env:
          ACTIVE_PROFILES: -Pjacoco,mutation-testing
          ADDITIONAL_MAVEN_ARGS: coveralls:report sonar:sonar
          COVERALLS_TOKEN: -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # Second job: also build on Java 9 and 11, but only after merging a PR
  build-on-pr-merge:
    if: startsWith(github.event.head_commit.message , 'Merge pull request')
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [9, 11]
    name: Build and test on Java ${{ matrix.java }}
    # Almost the same steps as first job (sadly, you can't yet reuse steps 
    # with Github Actions, so duplication is inevitable here)
    steps:
      - name: Check out latest code
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java_version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      # Avoid duplicated reports to sonar and coveralls
      - name: Run mvn clean verify (with jacoco and mutation testing)
        run: mvn -f pom.xml clean verify $ACTIVE_PROFILES
        env:
          ACTIVE_PROFILES: -Pjacoco,mutation-testing   
            
            
            
