# Automated Github release when a tag is pushed, uploading fatjar as an asset

name: Deploy

on:
  push:
    tags:
      - v*

jobs:

  deploy:

    runs-on: ubuntu-18.04
    name: Automated release with .jar

    steps:
      - name: Check out latest code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Package .jar (mvn clean package) skipping tests
        run: mvn -B -f pom.xml -DskipTests=true clean package
      - name: Create Github release with tag and upload fatjar as asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/*-jar-with-dependencies.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}